---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'È possibile aggiungere un"immagine ONTAP Select alla propria istanza dell"utility di amministrazione Deploy. Dopo che l"immagine è stata installata, è possibile utilizzarla quando si distribuisce un ONTAP Select cluster.' 
---
= Aggiungere un'immagine ONTAP Select da distribuire
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiungere un'immagine ONTAP Select alla propria istanza dell'utility di amministrazione Deploy. Dopo che l'immagine è stata installata, è possibile utilizzarla quando si distribuisce un ONTAP Select cluster.



== Prima di iniziare

Ad alto livello, il processo utilizzato per aggiungere un'immagine ONTAP Select a un'istanza di Deploy è costituito da quattro passaggi:

. Download dell'immagine di installazione
. Caricamento dell'immagine di installazione sulla macchina virtuale Deploy
. Aggiunta dell'immagine di installazione
. Visualizzazione delle immagini di installazione disponibili


Prima di aggiungere nuove immagini ONTAP Select da implementare, è necessario rimuovere tutte le immagini non necessarie.


NOTE: Aggiungere un'immagine ONTAP Select con una versione precedente alla versione originale inclusa nell'istanza dell'utilità di distribuzione. L'aggiunta di versioni più recenti di ONTAP Select non è una configurazione supportata.



== Scarica l'immagine di installazione

Per iniziare il processo di aggiunta di un'immagine ONTAP Select a un'istanza dell'utilità di implementazione, è necessario scaricare l'immagine di installazione dal sito del supporto NetApp. L'immagine di installazione di ONTAP Select viene formattata come singolo file compresso.

.Fasi
. Accedi al NetApp Support Site tramite un browser web e clicca su *Support Quick Links*.
. Fare clic su *Download Software* in *Top Tasks* e accedere al sito.
. Fai clic su *Find your product*.
. Scorri verso il basso e fai clic su *ONTAP Select*.
. In *Other Available Select Software* fare clic su *Deploy Upgrade, Node Upgrade, Image Install*.
. Seleziona la release desiderata del pacchetto di aggiornamento.
. Rivedi l'End User License Agreement (EULA) e fai clic su *Accetta & Continua*.
. Seleziona e scarica il pacchetto appropriato, rispondendo a tutte le richieste secondo le necessità del tuo ambiente.




== Carica l'immagine di installazione su Deploy

Dopo aver acquisito l'immagine di installazione di ONTAP Select, è necessario caricare il file sulla macchina virtuale di implementazione.

.Prima di iniziare
È necessario che il file immagine di installazione sia disponibile sulla workstation locale. È inoltre necessario disporre della password per l'account utente amministratore di Deploy.

.A proposito di questa attività
Questa attività descrive un metodo per caricare il file sulla macchina virtuale di implementazione. Potrebbero essere disponibili altre opzioni più adatte al proprio ambiente.

.Fase
. In una shell dei comandi sulla workstation locale, carica il file image sulla macchina virtuale Deploy.
+
Esempio

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Esempio

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Risultato
Il file di installazione del nodo viene memorizzato nella home directory dell'utente amministratore.



== Aggiungi l'immagine di installazione

È possibile aggiungere l'immagine di installazione di ONTAP Select alla directory Deploy images in modo che sia disponibile quando si distribuisce un nuovo cluster.

.Prima di iniziare
È necessario conoscere la directory in cui è stato inserito il file dell'immagine di installazione nella macchina virtuale dell'utility di implementazione. Si presuppone che il file si trovi nella home directory dell'amministratore.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore (admin).
. Avvia la shell Bash:
+
`shell bash`

. Posizionare il file install image nella directory images.
+
Esempio
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Visualizza le immagini di installazione disponibili

È possibile visualizzare le immagini ONTAP Select disponibili durante la distribuzione di un nuovo cluster.

.Fasi
. Accedere alla pagina Web della documentazione online dalla macchina virtuale dell'utility di implementazione e accedere utilizzando l'account Administrator (admin):
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilizzare il nome di dominio o l'indirizzo IP della macchina virtuale di implementazione.

. Vai in fondo alla pagina e clicca su *Deploy* e poi clicca su *GET /images*.
. Fare clic su *Provalo!* per visualizzare le immagini ONTAP Select disponibili.
. Verificare che l'immagine desiderata sia disponibile.

