---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 'È possibile aggiornare una macchina virtuale dell"utility di implementazione esistente in-place utilizzando l"interfaccia della riga di comando.' 
---
= Aggiornare un'istanza di implementazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile aggiornare una macchina virtuale dell'utility di implementazione esistente in-place utilizzando l'interfaccia della riga di comando.



== Prima di iniziare

Assicurarsi che Deploy non venga utilizzato per eseguire altre attività durante l'aggiornamento. È necessario consultare le note di rilascio correnti per informazioni e restrizioni sull'aggiornamento dell'utilità Deploy.


NOTE: Se è installata un'istanza precedente dell'utilità di amministrazione di distribuzione di ONTAP Select, è necessario eseguire l'aggiornamento alla versione corrente. Il nodo ONTAP Select e il componente di implementazione ONTAP Select vengono aggiornati in modo indipendente. Per ulteriori informazioni, vedere link:concept_adm_upgrading_nodes.html["Aggiornare i nodi ONTAP Select"^] .



== Scarica il pacchetto di aggiornamento

Per avviare il processo di aggiornamento, è necessario scaricare il file di aggiornamento della macchina virtuale Deploy appropriato dal NetApp Support Site. Il pacchetto di aggiornamento è formattato come un singolo file compresso.

.Fasi
. Accedi al link:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] utilizzando un browser web e scegli *Downloads* dal menu Downloads.
. Scorri verso il basso e seleziona *ONTAP Select Deploy Upgrade*.
. Seleziona la release desiderata del pacchetto di aggiornamento.
. Leggere il Contratto di licenza con l'utente finale (EULA) e selezionare *Accetta e continua*.
. Seleziona e scarica il pacchetto appropriato, rispondendo a tutte le richieste secondo le necessità del tuo ambiente.




== Carica il pacchetto sulla macchina virtuale Deploy

Dopo aver acquisito il pacchetto di upgrade, è necessario caricare il file sulla macchina virtuale Deploy.

.Prima di iniziare
È necessario che il file di aggiornamento sia disponibile sulla workstation locale. È inoltre necessario disporre della password per l'account utente amministratore.

.Informazioni su queste attività
Questa attività descrive un metodo per caricare il file sulla macchina virtuale di implementazione. Potrebbero essere disponibili altre opzioni più adatte al proprio ambiente.

.Fasi
. In una shell dei comandi sulla workstation locale, usa l'utilità scp per caricare il file immagine sulla macchina virtuale Deploy.
+
Esempio

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Risultato
Il file di aggiornamento viene memorizzato nella home directory dell'utente amministratore.



== Applica il pacchetto di aggiornamento

Dopo che il file di aggiornamento è stato caricato sulla macchina virtuale Deploy, è possibile applicare l'aggiornamento.

.Prima di iniziare
È necessario conoscere la directory in cui è stato posizionato il file di aggiornamento nella macchina virtuale dell'utility Deploy. Assicurarsi inoltre che Deploy non venga utilizzato per eseguire altre attività durante l'aggiornamento.

.Fasi
. Accedere alla CLI dell'utility di implementazione utilizzando SSH con l'account amministratore.
. Eseguire l'aggiornamento utilizzando il percorso di directory e il nome file appropriati:
+
`deploy upgrade -package-path FILEPATH`

+
Esempio

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Al termine
Prima del completamento della procedura di aggiornamento, ti verrà chiesto di creare un backup della configurazione della macchina virtuale Deploy. Inoltre, dovresti cancellare la cache del browser così da poter visualizzare le pagine Deploy appena create.
